server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service-route
              uri: http://patient-service:41111
              predicates:
                - Path=/api/patients/**

            - id: api-docs-patient-route
              uri: http://patient-service:41111
              predicates:
                - Path=/api-docs/patients