spring.application.name=Microservice

spring.datasource.url=jdbc:postgresql://localhost:5432/microservice
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=admin_viewer
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
server.port=41111

# Spring Security Configuration


# Disable JPA open in view warning
spring.jpa.open-in-view=false
logging.level.root=info
logging.level.com.example23.demo.exception=DEBUG
